# Generated by Django 3.2.25 on 2024-10-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceapp', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
